#!/bin/bash

function Drop_tb() {
 local current_dir=$(pwd)

 local DB_name=$(basename "$current_dir")

 local Tables_list=$(ls "$current_dir/")

  local selected_tb=$(yad --list  --width=300 --height=250 \
    --title="List of Tables in $DB_name.db" \
    --text="Choose a Table To Drop:" \
    --column="Tables" $Tables_list)

  local selected_tb=$(echo "$selected_tb" | awk -F'|' '{print $1}')
  if [ $? -eq 1 ]; then
    Table_menu $DB_name
    return
  fi

  yad --question --width=400 --height=100  --text="Are you sure you want to delete the Table '$DB_name.$selected_tb'?\nAll data inside this table will be permanently deleted."

  response=$?
  if [ $response -eq 0 ]; then
    rm -r "../$DB_name/$selected_tb/"
    yad --info --width=400 --height=100  --text="Database '$DB_name.$selected_tb' has been successfully deleted."
  else
    yad --info --width=400 --height=100  --text="Deletion of database '$DB_name.$selected_tb' has been canceled."
  fi
}

Drop_tb