#!/bin/bash

function Menu_Table() {
    while true; do
        selected_table=$(yad --list --width=300 --height=300 \
            --title="Table Menu" \
            --text="Choose an operation for the Database '$1':" \
            --column="Options" \
            "Create Table" \
            "List Tables" \
            "Drop Table" \
            "Insert Into Table" \
            "Select From Table" \
            "Delete From Table" \
            "Update Table" \
            "Disconnect From Database")

        if [ $? -eq 1 ]; then
            cd ../..
            echo "Current directory: $(pwd)"
            DBmenu
            return
        fi
        
        selected_table=$(echo "$selected_table" | awk -F'|' '{print $1}')
        
        case "$selected_table" in
            "Create Table" )
                source ../../Create_Table $1 ;;
            "List Tables" )
                source ../../List_Tables ;;
            "Drop Table" )
                source ../../Drop_Table ;;
            "Insert Into Table" )
                source ../../Insert_Table ;;
            "Select From Table" )
                source ../../Select_Table ;;
            "Delete From Table" )
                source ../../Delete_Data ;;
            "Update Table" )
                source ../../Update_Table ;;
            "Disconnect From Database" )
                cd ../..
                echo "Current directory: $(pwd)"
                DBmenu
                return ;;
            *)
                yad --error --width=400 --height=100 --text="Invalid choice. Please try again." ;;
        esac
    done
}

Menu_Table "$1"
#comment 1